version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.8
  orb-tools: circleci/orb-tools@10.0.2

jobs:
  pack:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/pack:
          source: src/
          destination: packed-orb.yml
      - orb-tools/validate:
          orb-path: packed-orb.yml
      - store_artifacts:
          path: packed-orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  publish:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - cli/install:
          debug: true
      - run:
          name: Add Github to known hosts
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v0-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Dependency Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v0-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Publish to CircleCI Orb Registry
          command: npm run semantic-release

workflows:
  btd:
    jobs:
      - pack

      - orb-tools/publish-dev:
          name: Development publish
          orb-name: goodwaygroup/circleci-orb
          orb-path: packed-orb.yml
          publish-token-variable: CIRCLECI_API_TOKEN
          publish-branch-sha-version: true
          attach-workspace: true
          workspace-root: .
          checkout: false
          requires: [pack]
          filters:
            branches:
              ignore: master

      - publish:
          requires: [pack]
          filters:
            branches:
              only: master